version: '3'
services:
  sql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'question_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'admin'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'toor'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'toor'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./db:/var/lib/mysql