services:
  nginx:
    image: nginx
    ports:
      - 50:80
    volumes:
      - ./src:/usr/share/nginx/html
    container_name: nginx
    restart: always

  node:
    image: node:latest
    command: sh -c 'npm install express && node && bcrypt .'
    volumes:
      - ./src/content/login/app.js:/app/index.js
      - ./src/content/login/public:/app/public
    working_dir: /app
    ports:
      - "1101:1101"

    